### ISSUE TITLE
Agradecimientos

### ISSUE THREAD

**Issue by gabriel1816** [Chabelamas/Prolog#1]
Resultó de extrema utilidad su resuelto mi estimada.

**Comment by Chabelamas** [comment]
Muchas gracias por todo el apoyo constante que me dan. Es por ustedes el por qué realizo todos estos exámenes. Sin ustedes no sería lo influencer que soy hoy en día, además de los canjes. Espero que promocionen o aprueben la materia. Nos veremos en el meet and greet el 24 de agosto. Un beso muy grande para cada uno de ustedes. @Chabelamas
